### ISSUE TITLE
在iphone se上拉刷新时报错

### ISSUE THREAD

**Issue by kyly1982** [GTMYang/GTMRefresh#1]
首先十分感谢你无私的开发这个库，能够让我在几乎不用更改tableview等的情况下直接使用，非常的方便省事，但是我在模拟器模拟的iphone se上运行时，在上拉松手后出错了，停止在GTMLoadMoreFooter中的第140行，既case willLoadMoreOffsetY...1000:这一行
原因是willLoadMoreOffsetY比1000大

此时的几个数据
currentOffsetY=1316.5
footerCloseOffsetY = 1264
willLoadMoreOffsetY=1314

另外提几个建议
1.希望在上拉加载更多中，isNoMoreData=true的情况下，footer的文字能有些优化，而不是提示加载更多
2.支持emptyview，在没有数据时要友好很多
3.能够添加个loadingview，在加载时显示loadingview

**Comment by GTMYang** [comment]
感谢你提出的建议，我会抽空调整

**Comment by GTMYang** [comment]
loadingview你可以用我的另外一个组件库：https://github.com/GTMYang/GTMActivityIndicatorView

**Comment by GTMYang** [comment]
缺陷已修复，请更新到最新版本

**Comment by GTMYang** [comment]
emptyview,因为各人项目里面的UI都需要定制，这个自己实现也很简单。也不属于Refresh的职能所在。
