### ISSUE TITLE
能不能把DefaultGTMLoadMoreFooter里面指示器白色背景注释了

### ISSUE THREAD

**Issue by bangjier** [GTMYang/GTMRefresh#12]
lazy var loaddingIndicator: UIActivityIndicatorView = {
        let indicator = UIActivityIndicatorView()
        indicator.hidesWhenStopped = true
        indicator.activityIndicatorViewStyle = .gray
        indicator.backgroundColor = UIColor.white
        
        return indicator
    }()
不然在tableView背景颜色不是白色的时候，这个指示器有个白色背景，看起比较怪；我看你把DefaultGTMRefreshHeader里面都注释了的

**Comment by GTMYang** [comment]
ok
