### ISSUE TITLE
一个严重的BUG

### ISSUE THREAD

**Issue by bangjier** [GTMYang/GTMRefresh#13]
在iOS9或者iOS10系统下，在二级页面添加刷新控件后，返回一级页面，程序会崩溃，在iOS11系统下不会；我测试了一下你的demo，一样会崩溃；主要是你在GTMRefreshComponent类里面使用KVO监听scrollView，页面返回后，scrollView对象已经销毁了，而你没有正常注销KVO，所以导致崩溃；麻烦大神处理一下

**Comment by GTMYang** [comment]
已修复
