### ISSUE TITLE
刷新文字无法显示中文，模拟器和真机都无法显示中文

### ISSUE THREAD

**Issue by bangjier** [GTMYang/GTMRefresh#14]

**Comment by GTMYang** [comment]
@bangjier 这个跟系统语言设置走的

**Comment by bangjier** [comment]
> @bangjier 这个跟系统语言设置走的
真机是中文，刷新的时候还是显示英文

**Comment by GTMYang** [comment]
@bangjier 可以手动设置
```swift
 var pullDownToRefresh = GTMRLocalize("pullDownToRefresh")
    var releaseToRefresh = GTMRLocalize("releaseToRefresh")
    var refreshSuccess = GTMRLocalize("refreshSuccess")
    var refreshFailure = GTMRLocalize("refreshFailure")
    var refreshing = GTMRLocalize("refreshing")
```

**Comment by bangjier** [comment]
> @bangjier 可以手动设置
> 
> ```swift
>  var pullDownToRefresh = GTMRLocalize("pullDownToRefresh")
>     var releaseToRefresh = GTMRLocalize("releaseToRefresh")
>     var refreshSuccess = GTMRLocalize("refreshSuccess")
>     var refreshFailure = GTMRLocalize("refreshFailure")
>     var refreshing = GTMRLocalize("refreshing")
> ```

在info.list添加Localized resources can be mixed将NO改为YES，使用系统语言就行了

**Comment by bangjier** [comment]
> @bangjier 可以手动设置
> 
> ```swift
>  var pullDownToRefresh = GTMRLocalize("pullDownToRefresh")
>     var releaseToRefresh = GTMRLocalize("releaseToRefresh")
>     var refreshSuccess = GTMRLocalize("refreshSuccess")
>     var refreshFailure = GTMRLocalize("refreshFailure")
>     var refreshing = GTMRLocalize("refreshing")
> ```

在info.list添加Localized resources can be mixed将NO改为YES，使用系统语言就行了

**Comment by bangjier** [comment]
> @bangjier 可以手动设置
> 
> ```swift
>  var pullDownToRefresh = GTMRLocalize("pullDownToRefresh")
>     var releaseToRefresh = GTMRLocalize("releaseToRefresh")
>     var refreshSuccess = GTMRLocalize("refreshSuccess")
>     var refreshFailure = GTMRLocalize("refreshFailure")
>     var refreshing = GTMRLocalize("refreshing")
> ```

在info.list添加Localized resources can be mixed将NO改为YES，使用系统语言就行了
