### ISSUE TITLE
一点小建议~

### ISSUE THREAD

**Issue by dearmiku** [GTMYang/GTMRefresh#17]
您好~ 在有时候 我们希望 cell 与 header 之间有一定间隙~ 我发现 框架中并没有这样的 属性进行设置~

**Comment by dearmiku** [comment]
![1](https://user-images.githubusercontent.com/26378870/49858612-543d7800-fe30-11e8-9dfa-355eacc201ac.png)
![screenshot](https://user-images.githubusercontent.com/26378870/49858613-54d60e80-fe30-11e8-835e-cb3eb25609ce.png)

如图~

**Comment by GTMYang** [comment]
@dearmiku 可以用TableView header 或者section header做
