### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by bangjier** [GTMYang/GTMRefresh#19]
我发现自定义FooterView后，自定义的FooterView比较高，用户要拉很高才能触发刷新，这样用户体验不好，希望能够自定义设置触发刷新的高度

**Comment by bangjier** [comment]
作者好久没更新了，说说我的解决方法：
把GTMRefreshHeader类中的willRefresHeight方法放到父类GTMRefreshComponent中，并在GTMLoadMoreFooter类中的scollViewContentOffsetDidChange方法中修改：let willLoadMoreOffsetY = footerCloseOffsetY + self.mj_h 为 let willLoadMoreOffsetY = footerCloseOffsetY + willRefresHeight()
在自定义的FooterView中重写willRefresHeight方法，返回触发刷新的高度
注意：如果使用cocoapods的，修改源码后，直接把文件导入项目中，不用cocoapods

**Comment by GTMYang** [comment]
@bangjier 增加了 willLoadMoreHeight() 方法
