### ISSUE TITLE
您好，内存泄漏问题

### ISSUE THREAD

**Issue by karidy** [GTMYang/GTMRefresh#2]
当加上
self.tableView?.gtm_addLoadMoreFooterView {
            [unowned self] in
            //print("excute loadMoreBlock")
            self.loadMore()
}
后，随着访问次数的增多，内存不断增加，当去掉这段代码后，内存使用正常，我不确定是不是该插件的问题。

**Comment by GTMYang** [comment]
谢谢,会尽快修复的

**Comment by GTMYang** [comment]
内存泄漏的问题已修复。block的方式查了很多天，没解决。暂时先改成delegate方式。
