### ISSUE TITLE
上拉和下拉时无法显示自定义文字？

### ISSUE THREAD

**Issue by w32831973** [GTMYang/GTMRefresh#24]
// text
self.tableView.pullDownToRefreshText("亲，试试下拉会刷新的")
.releaseToRefreshText("亲，松开试试")
.refreshSuccessText("亲，成功了")
.refreshFailureText("亲，无果")
.refreshingText("亲，正在努力刷新")

我直接复制这段代码，发现无效果，还是显示之前的英文文字。

**Comment by GTMYang** [comment]
时机不对，先创建好header再修改刷新文本
