### ISSUE TITLE
建议：

### ISSUE THREAD

**Issue by karidy** [GTMYang/GTMRefresh#3]
1. 当滚动到底部的时候，自动加载下一页数据，目前是需要往上拉后松开才能加载数据。
2.让下一页加载完后之后，刷新表格，整个表格会有向下滚动的操作，体验不是太好。
3.让加载到最后一页，提示信息目前是上拉，才能看见，我觉得滚动到底部的提示信息，可以一直显示，而不是上拉后才看得到。

**Comment by GTMYang** [comment]
已阅，抽空优化

**Comment by GTMYang** [comment]
@karidy 第1条考虑到用户流量到问题，加不加载更多还是交给用户决定比较好，所以不改进
第2条 这个目前我没有好第解决方案，可否有好第解决方案提供？
第3条  已做调整
