### ISSUE TITLE
GTMRefreshComponent类里面的scrollView键值观测没有被释放

### ISSUE THREAD

**Issue by cowboyfzl** [GTMYang/GTMRefresh#5]
failed: failed: caught "NSInternalInconsistencyException", "An instance 0x7ffbb701f400 of class UITableView was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x60800003dcc0> (
<NSKeyValueObservance 0x608000246c00: Observer: 0x7ffbb6556580, Key path: contentOffset, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x608000054550>
<NSKeyValueObservance 0x608000250650: Observer: 0x7ffbb6556580, Key path: contentSize, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x6080000547c0>
<NSKeyValueObservance 0x608000248eb0: Observer: 0x7ffbb6553560, Key path: contentOffset, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x608000054550>
<NSKeyValueObservance 0x60800024ff30: Observer: 0x7ffbb6553560, Key path: contentSize, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x6080000547c0>

跑TEST的时候提示scrollView所添加的kvo没有被释放……麻烦你修改一下这个bug
或者换个思路，能否通过其他方式传值？

**Comment by GTMYang** [comment]
@cowboyfzl  什么样的环境上跑的？我需要重现一下错误

**Comment by GTMYang** [comment]
@cowboyfzl 新版本你再看一下
