### ISSUE TITLE
viewDidload中添加header，push到新页面的时候，header不见了

### ISSUE THREAD

**Issue by fisland** [GTMYang/GTMRefresh#6]
在demo上也试过，除非写到viewDidAppear那里。
不过写到appear那里的话，如果有present vc的操作，返回再下拉头部，程序崩溃

**Comment by fisland** [comment]
header在push到新页面的时候，应该是被释放掉了

**Comment by GTMYang** [comment]
已阅 会修复

**Comment by GTMYang** [comment]
问题已修复，请更新到最新版本
