### ISSUE TITLE
对象没有释放

### ISSUE THREAD

**Issue by limxing** [GTMYang/GTMRefresh#9]
DefaultGTMRefreshHeader没有被释放，你们有这种情况吗？

**Comment by GTMYang** [comment]
@limxing  我看下

**Comment by limxing** [comment]
@GTMYang 解决了，GTMRefreshComponent 中的  public weak var scrollView: UIScrollView?  弱引用就可以啦

**Comment by GTMYang** [comment]
@limxing 3Q
